####
# GitLab CI
####

# Image
image: openjdk:8-jdk-alpine

# Cache
cache:
  key: gradle
  paths:
  - .gradle/wrapper
  - .gradle/caches

services:
- docker:dind

variables:
  # Note that if you're using Kubernetes executor, the variable should be set to
  # tcp://localhost:2375 because of how Kubernetes executor connects services
  # to the job container
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

# Stages
stages:
- build
- test
- docker
- docs
- publishStage
- publishStable

# Build
Assemble:
  stage: build
  script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - ./gradlew assemble
  artifacts:
    paths:
    - cli-deploy/build/libs
    - rest-deploy/build/libs
    expire_in: 1 week

# Test
Run Tests:
  stage: test
  script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - ./gradlew test

# Docker
Assemble CLI Docker Container:
  image: docker:stable
  stage: docker
  script:
  - cp cli-deploy/build/libs/*.jar cli-deploy/docker/rootfs/app.jar
  - docker build -t $CI_REGISTRY_IMAGE/cli:$CI_COMMIT_REF_SLUG cli-deploy/docker
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker push $CI_REGISTRY_IMAGE/cli:$CI_COMMIT_REF_SLUG

# Docker
Assemble REST Docker Container:
  image: docker:stable
  stage: docker
  script:
  - cp rest-deploy/build/libs/*.jar rest-deploy/docker/rootfs/app.jar
  - docker build -t $CI_REGISTRY_IMAGE/rest:$CI_COMMIT_REF_SLUG rest-deploy/docker
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker push $CI_REGISTRY_IMAGE/rest:$CI_COMMIT_REF_SLUG

###
# Pre-Release
###
Publish Prerelease:
  stage: publishStage
  script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - ./gradlew artifactoryPublish -Dsnapshot=true
  only:
  - /^v[0-9]+\.[0-9]+\.[0-9]+\-alpha\.[0-9]+$/
  - /^v[0-9]+\.[0-9]+\.[0-9]+\-beta\.[0-9]+$/
  - /^v[0-9]+\.[0-9]+\.[0-9]+\-rc\.[0-9]+$/

###
# Stable Release
###
Publish Release:
  stage: publishStable
  script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - ./gradlew bintrayUpload
  only:
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/
